pipeline {
    agent any
    stages {
        stage('Build') {
	tools{
		maven 'localMaven'
	}
            steps {
                //sh 'mvn -B -DskipTest clean package'
		sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
